# Generated by Django 4.1.2 on 2022-10-11 19:40

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_alter_category_parent"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="is_active",
            new_name="active",
        ),
        migrations.AlterField(
            model_name="category",
            name="parent",
            field=mptt.fields.TreeForeignKey(
                blank=True,
                help_text="",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="store.category",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(
                help_text="Required", max_length=255, verbose_name="Name"
            ),
        ),
    ]
